services:
  - type: web
    name: url-shortener
    env: python
    plan: free
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python shorten.py"
    autoDeploy: true